name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - name: Install dependencies
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev cmake
    - name: Run CMake
      run: mkdir build && cd build && cmake ..
    - name: Run make
      run: make
