name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update VM
        run: sudo apt update && sudo apt upgrade
      - name: Install dependencies
        run: sudo apt-get install python3 python3-pip python3-setuptools \
          python3-wheel ninja-build
      - name: Install meson
        run: pip3 install meson
      - name: Setup Meson
        run: meson setup builddir && cd builddir
      - name: Compile
        run: meson compile
